# Copyright 2023 Atakku <https://atakku.dev>
#
# This project is dual licensed under MIT and Apache.

[package]
name = "s2fa"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
actix-web = "4.9.0"
steam-totp = "0.2.2"
