# Copyright 2023 Atakku <https://atakku.dev>
#
# This project is dual licensed under MIT and Apache.

[package]
name = "s2fa"
version = "0.0.1"
edition = "2021"

[dependencies]
actix-web = "4.4"
steam-totp = "0.2"
